apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    apps: influxdb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb-img
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        volumeMounts:
          - name: influxdb-volume
            mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-volume

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi